---
title: "BIO611 Final Project Analysis & Viz"
author: "Briana Roberson"
date: "2026-04-20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r load libraries and packages, set plotting theme}
library(dplyr)
library(ggplot2)
library(maps)
library(rcartocolor)
library(sf)


theme<-theme(
      plot.title = element_text(face="bold", size = 18, hjust = 0.5),
      axis.title.y = element_text(face="bold", size = 12), 
      axis.text.y = element_text(size = 12),
      axis.title.x = element_text(size = 12, face = "bold",color = "black"),
      axis.text.x=element_text(size=12),
      plot.margin = unit(c(0.1,0.1,0,0.1),"cm"))

#Hex color bank for visualizations: 
#0a688a blue

```

## First visualization: Observations of tricolored bats over time using GBIF species occurrence data

```{r bat map data exploration}

bat_occ <- data.table::fread("0032207-260409193756587.csv") #This is the dataset for the entire United States occurrences 
str(bat_occ)

#Many occurrences do not include coordinates or lie outside the US, so I filter those out here 
bat_map <- bat_occ[
  !is.na(decimalLatitude) & 
  !is.na(decimalLongitude) &
  decimalLatitude >= 27 & decimalLatitude <= 45 &
  decimalLongitude >= -125 & decimalLongitude <= -66
]

str(bat_map)
```


```{r creating the map}

bat_map_viz <- ggplot(bat_map, aes(x = decimalLongitude, y = decimalLatitude, color = year)) +
   borders("state", fill = "white", color = "black") +
  geom_point(size = 2, alpha = 0.8) +
  scale_color_carto_c(palette = "Earth") +
  coord_fixed(1.3) +
  theme(
    panel.grid = element_blank(), 
    panel.background = element_blank()
  ) +
  labs(
       color = "Year", 
  x = "decimal Longitude (°)",
  y = "decimal Latitude (°)"
) + 
  theme 

bat_map_viz

```
## Now let's actually work with the main data 

```{r data exploration}
batmass <- read.csv("Tricolored_Biometric_Database.csv")

#Take a peek 
summary(batmass)
str(batmass)

#When did sampling occur? 
unique(batmass$year)

#This data includes caves and culverts, so I will filter for culverts only 
batmass_filt <- batmass %>%
  filter(type == "Culvert")
str(batmass_filt)
unique(batmass_filt$type) #worked 

#How many culverts are there? 
unique(batmass_filt$site) #29


```
```{r culvert locations}
#longitude is actually misspelled so I'll fix that before mapping 
names(batmass)[names(batmass) == "Longitide"] <- "Longitude"
str(batmass)

#transform coordinates to a referenced sf object
culvert_sf <- st_as_sf(df,
                  coords = c("Longitude", "Latitude"),
                  crs = 4326)  # WGS84 lat/long


```

